Routes and Protected routes for App added
17u5h/track-pack pull request #4
Opened 2022-09-24 18:21 UTC by 17u5h

2022-09-26 06:07 UTC, mrerberg requested changes

2022-09-26 06:07 UTC, mrerberg commented on src/routes.tsx
> +	if (localStorage['isLogin'] === null) throw new Error('проблема с логином, он null')
А зачем это строка? Если не будет isLogin, то пользака редиректнет в неавторизованную зону и все

2022-09-26 06:07 UTC, mrerberg commented on src/routes.tsx
> +		</Routes>
<Route path="*" element={<NotFound/>}/>

2022-09-26 06:07 UTC, mrerberg commented on src/routes.tsx
> +		</Routes>
Не нужны скобки вокруг строки

2022-09-26 06:07 UTC, mrerberg commented on src/routes.tsx
> +		</Routes>
Это можно в линтерах настроить

2022-09-26 06:07 UTC, mrerberg commented on src/pages/selection/SelectionScreen.tsx
> +export function SelectionScreen(){
Что имелось ввиду под этим названием?

2022-09-26 06:07 UTC, mrerberg commented on src/pages/not-found/index.tsx
> +			<h1>404</h1>
На странице может быть только 1 h1

2022-09-26 06:07 UTC, mrerberg commented on src/pages/main/index.tsx
> +      <S.GlobalStyle/>
Зачем ты вставляешь глобальные стили на каждую страницу? Вставь в компонент App 1 раз и все

2022-09-26 06:07 UTC, mrerberg commented on src/pages/main/NavMenuLink.tsx
> +type types ={
Во-первых, типы и интерфейсы пишутся с большой буквы. Во-вторых, принято именовать как Props, если тип не экспортируется. так же есть встроенные тип для компонента, имеющего children

```
export const NavMenuLink: React.FC = ({children}) => ...
```

2022-09-26 06:59 UTC, 17u5h commented on src/routes.tsx
> +	if (localStorage['isLogin'] === null) throw new Error('проблема с логином, он null')
хмм, и действительно. 
Эта строка была унаследована от старого кода. Машинопись ругалась, что переменная is possibly 'null'. 
Удалил эту троку

2022-09-26 07:01 UTC, 17u5h commented on src/routes.tsx
> +		</Routes>
займусь настройкой линтера. 
Да, я знаю, что фигурные скобки не обязательны. Просто мне Вебшторм их сам рисует после знака равно. Ну я и не парюсь удалять)

2022-09-26 07:02 UTC, 17u5h commented on src/pages/selection/SelectionScreen.tsx
> +export function SelectionScreen(){
это я пытался придумать английский аналог слову "подборки". Не смог придумать ничего лучше(

2022-09-26 07:02 UTC, 17u5h commented on src/pages/not-found/index.tsx
> +			<h1>404</h1>
ох ты ж блин, точно... как-то вылетело из головы

2022-09-26 07:03 UTC, 17u5h commented on src/pages/main/index.tsx
> +      <S.GlobalStyle/>
а что так можно было?)
Тогда наверно похожей схемой можно и layоut сделать?

2022-09-26 07:04 UTC, 17u5h commented on src/pages/main/NavMenuLink.tsx
> +type types ={
вот за эту инфу спасибо! А я всё думаю как же лучше назвать и написать

2022-09-27 05:58 UTC, mrerberg commented on src/pages/selection/SelectionScreen.tsx
> +export function SelectionScreen(){
Collection?

2022-09-27 05:58 UTC, mrerberg commented on src/pages/main/index.tsx
> +      <S.GlobalStyle/>
Конечно

2022-09-27 05:59 UTC, mrerberg requested changes

2022-09-27 05:59 UTC, mrerberg commented on src/components/protected-route/index.tsx
> +type propTypes = {
Пинг на название

2022-09-27 05:59 UTC, mrerberg commented on src/pages/main/styles.js
> +	color: #FFFFFF;
Что с форматированием?

2022-09-27 06:33 UTC, mrerberg approved these changes

2022-09-27 06:36 UTC, 17u5h commented on src/pages/main/styles.js
> +	color: #FFFFFF;
да) ускакало одеяло, убежала простыня...

2022-09-27 06:38 UTC, merged